BufeteBundle\Entity\Personas:
    type: entity
    table: personas
    indexes:
        IX_Relationship13:
            columns:
                - Id_Bufete
    id:
        idPersona:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id_Persona
            generator:
                strategy: IDENTITY
    fields:
        nombrePersona:
            type: string
            nullable: false
            length: 75
            options:
                fixed: false
            column: Nombre_Persona
        telefonoPersona:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: Telefono_Persona
        direccionPersona:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
            column: Direccion_Persona
        emailPersona:
            type: string
            nullable: true
            length: 75
            options:
                fixed: false
            column: Email_Persona
        usuarioPersona:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
            column: Usuario_Persona
        contraseñaPersona:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
            column: Contraseña_Persona
        estadoPersona:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: Estado_Persona
        role:
            type: string
            nullable: false
            length: 75
            options:
                fixed: false
    manyToOne:
        idBufete:
            targetEntity: Bufetes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Id_Bufete:
                    referencedColumnName: Id_Bufete
            orphanRemoval: false
    lifecycleCallbacks: {  }
