bufete_paises:
    resource: "@BufeteBundle/Resources/config/routing/paises.yml"
    prefix:   /paises

bufete_homepage:
    path:     /
    defaults: { _controller: BufeteBundle:Default:index }

bufete_departamentos:
        resource: "@BufeteBundle/Resources/config/routing/departamentos.yml"
        prefix:   /departamentos

bufete_ciudad:
        resource: "@BufeteBundle/Resources/config/routing/ciudad.yml"
        prefix:   /ciudad
