bufete:
    resource: "@BufeteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

Paises:
    resource: "@BufeteBundle/Resources/config/routing/paises.yml"
    prefix:     /paises


Prestaciones:
    resource: "@BufeteBundle/Resources/config/routing/prestaciones.yml"
    prefix:     /prestaciones

Pretenciones:
    resource: "@BufeteBundle/Resources/config/routing/pretenciones.yml"
    prefix:     /pretenciones

Tribunales:
    resource: "@BufeteBundle/Resources/config/routing/tribunales.yml"
    prefix:     /tribunales

Tipoasuntos:
    resource: "@BufeteBundle/Resources/config/routing/tipoasuntos.yml"
    prefix:     /tipoasuntos

Tipocaso:
    resource: "@BufeteBundle/Resources/config/routing/tipocaso.yml"
    prefix:     /tipocaso

Bufetes:
    resource: "@BufeteBundle/Resources/config/routing/bufetes.yml"
    prefix:     /bufetes

Demandantes:
    resource: "@BufeteBundle/Resources/config/routing/demandantes.yml"
    prefix:     /demandantes

Departamentos:
    resource: "@BufeteBundle/Resources/config/routing/departamentos.yml"
    prefix:     /departamentos

Ciudades:
    resource: "@BufeteBundle/Resources/config/routing/ciudad.yml"
    prefix:     /ciudad

EstadosCiviles:
    resource: "@BufeteBundle/Resources/config/routing/estadosciviles.yml"
    prefix:     /estadosciviles

Trabajos:
    resource: "@BufeteBundle/Resources/config/routing/trabajos.yml"
    prefix:     /trabajos

Demandados:
    resource: "@BufeteBundle/Resources/config/routing/demandados.yml"
    prefix:     /demandados

Personas:
    resource: "@BufeteBundle/Resources/config/routing/personas.yml"
    prefix:     /personas

Estudiantes:
    resource: "@BufeteBundle/Resources/config/routing/estudiantes.yml"
    prefix:     /estudiantes

Casos:
    resource: "@BufeteBundle/Resources/config/routing/casos.yml"
    prefix:     /casos
