bufetes_index:
    path:     /
    defaults: { _controller: "BufeteBundle:Bufetes:index" }
    methods:  GET

bufetes_show:
    path:     /{id}/show
    defaults: { _controller: "BufeteBundle:Bufetes:show" }
    methods:  GET

bufetes_new:
    path:     /new
    defaults: { _controller: "BufeteBundle:Bufetes:new" }
    methods:  [GET, POST]

bufetes_edit:
    path:     /{id}/edit
    defaults: { _controller: "BufeteBundle:Bufetes:edit" }
    methods:  [GET, POST]

bufetes_delete:
    path:     /{id}/delete
    defaults: { _controller: "BufeteBundle:Bufetes:delete" }
    methods:  DELETE
