ciudad_index:
    path:     /
    defaults: { _controller: "BufeteBundle:Ciudad:index" }
    methods:  GET

ciudad_show:
    path:     /{id}/show
    defaults: { _controller: "BufeteBundle:Ciudad:show" }
    methods:  GET

ciudad_new:
    path:     /new
    defaults: { _controller: "BufeteBundle:Ciudad:new" }
    methods:  [GET, POST]

ciudad_edit:
    path:     /{id}/edit
    defaults: { _controller: "BufeteBundle:Ciudad:edit" }
    methods:  [GET, POST]

ciudad_delete:
    path:     /{id}/delete
    defaults: { _controller: "BufeteBundle:Ciudad:delete" }
    methods:  DELETE
