laborales_index:
    path:     /
    defaults: { _controller: "BufeteBundle:Laborales:index" }
    methods:  GET

laborales_show:
    path:     /{id}/show
    defaults: { _controller: "BufeteBundle:Laborales:show" }
    methods:  GET

laborales_new:
    path:     /new
    defaults: { _controller: "BufeteBundle:Laborales:new" }
    methods:  [GET, POST]

laborales_edit:
    path:     /{id}/edit
    defaults: { _controller: "BufeteBundle:Laborales:edit" }
    methods:  [GET, POST]

laborales_delete:
    path:     /{id}/delete
    defaults: { _controller: "BufeteBundle:Laborales:delete" }
    methods:  DELETE
