personas_index:
    path:     /
    defaults: { _controller: "BufeteBundle:Personas:index" }
    methods:  GET

personas_show:
    path:     /{id}/show
    defaults: { _controller: "BufeteBundle:Personas:show" }
    methods:  GET

personas_new:
    path:     /new
    defaults: { _controller: "BufeteBundle:Personas:new" }
    methods:  [GET, POST]

personas_edit:
    path:     /{id}/edit
    defaults: { _controller: "BufeteBundle:Personas:edit" }
    methods:  [GET, POST]

personas_delete:
    path:     /{id}/delete
    defaults: { _controller: "BufeteBundle:Personas:delete" }
    methods:  DELETE
