AppBundle\Entity\Civiles:
    type: entity
    table: civiles
    indexes:
        IX_Relationship8:
            columns:
                - Id_Pretencion
        IX_Relationship22:
            columns:
                - Id_Caso
    id:
        idCivil:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id_Civil
            generator:
                strategy: IDENTITY
    fields:
        estadoCivil:
            type: boolean
            nullable: false
            column: Estado_Civil
    manyToOne:
        idCaso:
            targetEntity: Casos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Id_Caso:
                    referencedColumnName: Id_Caso
            orphanRemoval: false
        idPretencion:
            targetEntity: Pretenciones
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Id_Pretencion:
                    referencedColumnName: Id_Pretencion
            orphanRemoval: false
    lifecycleCallbacks: {  }
